version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - run: bundle install
      - run: yarn install
      - run: bundle exec rake db:schema:load
      - run: COVERALLS_REPO_TOKEN=03URB11QBLDwQI0ftkDSQpyLWx7Wo5vYu bundle exec rails test

