version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
    steps:
      - checkout
      - run: gem i bundler
      - run: bundle install
      - run: yarn install
      - run: COVERALLS_REPO_TOKEN=03URB11QBLDwQI0ftkDSQpyLWx7Wo5vYu bundle exec rails test

